server:
  serverName: zrpc
  port: 9090
  runMode: debug # release debug
  logLevel: debug # debug info warn error
  logPath: runtime/logs # path 日志文件路径
  readTimeout: 30 # 读超时 秒
  writeTimeout: 30 # 写超时 秒
  shutdownTime: 5 # 优雅停止程序 秒
  workerID: 1 # 雪花算法分布式的当前 workerID
  jwtSecret: c58c3baeb4483b9255013bec45678bd6 # JWT 密钥  zhyu-go-1659263420

database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password:
  dbname: test
  max_idle_conn: 10
  max_open_conn: 30
  conn_max_lifetime: 300

redis:
  host: localhost
  port: 6379
  password:
  db: 0
  poolSize: 100

elastic:
  host: http://127.0.0.1:9200/
  user: elastic
  password: zj123123

whiteList:
  ip:
    - ::1
    - 127.0.0.1
    - 192.168.0.3